# Utilizar una imagen base de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /home/config/Proyecto-Dockerizado-con-ETL-Oracle-y-PostgreSQL/DATA_INTEGRATION_REQ

# Copiar los archivos necesarios al contenedor
COPY . .

# Instalar bash si no está presente
RUN apt-get update && apt-get install -y bash

# Ejecutar el script de Python
CMD ["python", "Rapp.py"]
